name: Slow tests on important models

on:
  push:
    branches: [ test-younes-workflow ]

env:
  RUN_SLOW: "yes"
  IS_GITHUB_CI: "1"
  SLACK_API_TOKEN: ${{ secrets.SLACK_CIFEEDBACK_BOT_TOKEN }}$


jobs:
  get_modified_models:
    name: "Get all modified files"
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@3f54ebb830831fc121d3263c1857cfbdc310cdb9 #v42
        with:
          files: src/transformers/models/**
          json: "true"
      - name: Run step if only the files listed above change
        if: steps.changed-files.outputs.any_changed == 'true'
        id: set-matrix
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files}}; do
            echo "$file was changed"
          done 
          echo "matrix=${{ steps.changed-files.outputs.all_changed_files}}" >> $GITHUB_OUTPUT

  run_all_tests_single_gpu:
    needs: get_modified_models
    runs-on: [self-hosted, single-gpu, nvidia-gpu, a10, push-ci]
    container:
      image: huggingface/transformers-all-latest-gpu
      options: --gpus all --shm-size "40gb" -e NVIDIA_DISABLE_REQUIRE=true